### PR TITLE
Added An Example to show the use of Rainbow text with an Array output

### PR DESCRIPTION
**Pull request by NicholasBlackburn1**
Added An Sample to show users how to use rainbow text with an array and a for a loop.

### CODE REVIEW

**Comment by NicholasBlackburn1** [comment]
Finished one Sample use of the library

**Comment by willmcgugan** [comment]
What feature of Rich does this demonstrate?

**Comment by NicholasBlackburn1** [comment]
this demonstrates on how to use the rainbow text in an supplementary way to the orginal rainbow text example.

**Review by NicholasBlackburn1 — COMMENTED** [review]
Fixed Misleading file name to rainbowArrays to Comply with python standards.

**Comment by willmcgugan** [comment]
Sorry. I don't think this adds any value. Examples should demonstrate a feature not already covered.

**Pull request closed without merging**
