### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by tusharsadhwani**
## Type of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [x] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [x] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Removes unused imports. These imports were unused by mypy as well.

### CODE REVIEW

**Comment by tusharsadhwani** [comment]
Hm, it seems that `poetry install` is failing because poetry v1.1.6 transitively depends on some older version of `setuptools_scm` which was broken?

[poetry 1.1.7](https://github.com/python-poetry/poetry/releases/tag/1.1.7) release notes mention something about it, maybe updating poetry to 1.1.7 (or latest, 1.1.8) would fix it?

**Comment by willmcgugan** [comment]
@tusharsadhwani Hmm. Do you want to try bumping poetry?

**Comment by tusharsadhwani** [comment]
in the same pr, or a new one?

**Comment by willmcgugan** [comment]
Same PR works for me.

**Comment by tusharsadhwani** [comment]
Alright that worked :D

**Comment by willmcgugan** [comment]
Fantastic, good call.

**Comment by willmcgugan** [comment]
Thanks!

**Pull request merged**
