### PR TITLE
Add stdin support to rich.json

### PR DESCRIPTION
**Pull request by tusharsadhwani**
## Type of changes

- [ ] Bug fix
- [x] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Add support for `rich.json` to read input from stdin (eg. pipes) when no file name is provided.

### CODE REVIEW

**Comment by tusharsadhwani** [comment]
- Unsure if I could add a test for this.
- Does this really warrant adding myself to `contributors.md`?

**Comment by willmcgugan** [comment]
The other commands `python -m syntax`, and `python -m markdown` use a different convention, where if the path is `-` then it reads from stdin. Probably best to use that for consistency sake.

I haven't added tests for these "__main__" blocks. I consider them a demo more than anything else, not the core lib. That might change in the future, but for now its fine not to test this.

Yeah, please add yourself to contributors.md!

**Comment by tusharsadhwani** [comment]
Yeah I should've noticed the mention of `'-'` in the help string of the `PATH` argument. Thanks!

**Comment by willmcgugan** [comment]
Fantastic. One last thing, would you mind adding a new Unreleased entry at the top of changelog.md?

**Comment by tusharsadhwani** [comment]
Done ✨

**Comment by willmcgugan** [comment]
LGTM. Thanks Tushar.

**Pull request merged**
