### PR TITLE
Translation of the README into French

### PR DESCRIPTION
**Pull request by p0lux**
## Type of changes

- [ ] Bug fix
- [ ] New feature
- [x] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [ ] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Translation of the README into French

### CODE REVIEW

**Comment by willmcgugan** [comment]
This is great. Merci!

Would you mind updating README.md to link to the French version?

**Comment by willmcgugan** [comment]
Also if you wouldn't mind could you edit codespell.yml to exclude the French readme?

**Comment by willmcgugan** [comment]
That's great. Thanks again!

**Comment by p0lux** [comment]
With pleasure, glad to have been able to help the community!

**Pull request merged**
