### PR TITLE
Fix missing reflinks from changelog

### PR DESCRIPTION
**Pull request by glensc**
## Type of changes

- [ ] Bug fix
- [ ] New feature
- [x] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [ ] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [ ] I accept that @willmcgugan may be pedantic in the code review.

## Description

Fixes incomplete changelog: missing markdown reflinks.

image

### CODE REVIEW

**Comment by glensc** [comment]
With some scripting could finish the rest of the entries,  if the change is going to be accepted.

Didn't want to pour too much time into this if the change is not accepted, but just looks like somebody did not notice the ref-links are missing.

**Comment by willmcgugan** [comment]
If you want to go to the trouble, no objections from me.

**Comment by glensc** [comment]
Went the easy way, filling the rest of them at bottom of the file.

**Comment by glensc** [comment]
The command

```
grep -F '## [' CHANGELOG.md |awk '{print $2}'|tr -d ']['| while read v; do echo "[$v]: https://github.com/willmcgugan/rich/compare/v$v...v$p"; p=$v; done >> CHANGELOG.md
```

**Comment by glensc** [comment]
@willmcgugan anything else?

**Comment by willmcgugan** [comment]
LGTM. Thanks.

**Comment by glensc** [comment]
Don't forget to fill one for `[10.15.1]`

**Pull request merged**
