### PR TITLE
Add checkMark and crossMark status

### PR DESCRIPTION
**Pull request by davidbrochart**
## Type of changes

- [ ] Bug fix
- [x] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

This allow to mark a status as "done" or "failed" with a check mark or a cross mark instead of a spinner:
```python
status.update("Done", spinner="checkMark")
status.update("Failed", spinner="crossMark")
```
✅ Done
❌ Failed

### CODE REVIEW

**Comment by willmcgugan** [comment]
Not sure why you would need that. Presumably once you are done, you can exit the status context and print whatever you like?

**Comment by davidbrochart** [comment]
I'm using a live tree that represents running tasks, with subtasks down in the hierarchy, so I need to flag tasks as done or failed, but the tree rendering still goes on.

**Comment by davidbrochart** [comment]
> you can exit the status context and print whatever you like

Maybe there's a better way to do it, but I want to change the status in-place to "done" or "failed".

**Comment by willmcgugan** [comment]
Fair enough. Seems like a reasonable solution.

**Comment by willmcgugan** [comment]
Actually, it may be a little top specific. I can imagine other users wanting different unicode symbols and I couldn't add a spinner for all requirements.

Could you replace the spinner with `Text("✅ Done")` (or cross) as needed?

**Comment by davidbrochart** [comment]
I'm not sure to understand, do you mean something like:
```python
status.update("✅ Done")
```
But then we still have a leading spinner?

**Comment by willmcgugan** [comment]
I meant replace status instance with a new Text instance.

If you have a Tree node (returned from Tree.add) you can do this:

```python
tree_node.label = "✅ Done"
```

Which will replace the status with Text.

Alternatively you could implement a renderable that returns a Spinner or the desired text. Something along these lines:

```python
class MyLabel:
    def __init__(self):
        self.spinner = Spinner()
    
    def __rich__(self):
        if is_finished():
            return "Done" if status == "done" else "Fail"
        else:
            return self.spinner

tree = Tree()
tree.add(MyLabel())
```

**Comment by davidbrochart** [comment]
> If you have a Tree node (returned from Tree.add) you can do this:
> 
> ```python
> tree_node.label = "✅ Done"
> ```
> 
> Which will replace the status with Text.

Works like a charm, thanks a lot.
This is my first day using Rich, and it's awesome :smile:

**Pull request closed without merging**
