### PR TITLE
Removes unused imports

### PR DESCRIPTION
**Pull request by sondrelg**
## Type of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [x] Other

## Checklist

- [x] I've run the latest [black](https://github.com/ambv/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

I just stumbled onto some unused imports in some of the project files when I was implementing the rich logging handler; thought you might like them removed. 

image

Also took the liberty of adding black as a dev dependency, seeing that it's a formalized part of the project PRs.

### CODE REVIEW

**Comment by willmcgugan** [comment]
Thanks, I should set up linting to find these in future. 

I'm getting a number of test fails. You can run tests with `make test`. Looks like a little too much pruning of imports...

**Comment by willmcgugan** [comment]
I've just enabled the tests to run on pull request with Github Actions. So hopefully test errors will show up here.

**Comment by sondrelg** [comment]
I will definitely make an attempt at getting all the tests passing, the way they're meant to. However, when running tests in the current master branch I have the same number of failing tests as I do in the fork (23). 

Do tests fail for you in the master branch? If not, perhaps it's a poetry issue?

**Comment by willmcgugan** [comment]
That’s strange! Tests on master pass for me locally on OSX, and in Github Actions. Can you give me an example of the failing tests?

What platform, Python version, are you using.

**Comment by sondrelg** [comment]
Windows, and Python 3.8. Most likely I'm assuming something I shouldn't, so here's what I've done (using the original master branch) :)

- I pull master, 
- run `poetry install`, 
- activate the venv, 

and then I *would* `make test`, but I'm on windows, so instead I just found the executing command `pytest --cov-report term-missing --cov=rich tests/ -vv`. Since pytest isn't listed in the `pyproject.toml` I need to install pytest and pytest-cov to make tests run.

The result of running the tests is `23 failed, 188 passed in 6.20s `

--------------

[This ](https://github.com/willmcgugan/rich/blob/master/tests/test_bar.py#L32) test is one that fails for me in both cases. 

Full test output

```
============================= test session starts =============================
platform win32 -- Python 3.8.2, pytest-5.4.3, py-1.8.2, pluggy-0.13.1 -- C:\Users\Sondre\Repos\temp\rich\.venv\Scripts\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\Sondre\Repos\temp\rich\tests, inifile: pytest.ini
plugins: cov-2.10.0
collecting ... collected 1 item

test_bar.py::test_render FAILED                                          [100%]
test_bar.py:31 (test_render)
\x1b[38;2;249;38;114m▓▓▓▓▓\x1b[0m\x1b[38;2;249;38;114m░\x1b[0m\x1b[38;5;237m▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓\x1b[0m != \x1b[38;2;249;38;114m━━━━━\x1b[0m\x1b[38;2;249;38;114m╸\x1b[0m\x1b[38;5;237m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\x1b[0m

Expected :\x1b[38;2;249;38;114m━━━━━\x1b[0m\x1b[38;2;249;38;114m╸\x1b[0m\x1b[38;5;237m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\x1b[0m
Actual   :\x1b[38;2;249;38;114m▓▓▓▓▓\x1b[0m\x1b[38;2;249;38;114m░\x1b[0m\x1b[38;5;237m▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓\x1b[0m
<Click to see difference>

def test_render():
        bar = Bar(completed=11, width=50)
        bar_render = render(bar)
>       assert bar_render == expected[0]
E       AssertionError: assert '\x1b[38;2;249;38;114m▓▓▓▓▓\x1b[0m\x1b[38;2;249;38;114m░\x1b[0m\x1b[38;5;237m▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓\x1b[0m' == '\x1b[38;2;249;38;114m━━━━━\x1b[0m\x1b[38;2;249;38;114m╸\x1b[0m\x1b[38;5;237m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\x1b[0m'

test_bar.py:35: AssertionError


================================== FAILURES ===================================
_________________________________ test_render _________________________________

    def test_render():
        bar = Bar(completed=11, width=50)
        bar_render = render(bar)
>       assert bar_render == expected[0]
E       AssertionError: assert '\x1b[38;2;249;38;114m▓▓▓▓▓\x1b[0m\x1b[38;2;249;38;114m░\x1b[0m\x1b[38;5;237m▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓\x1b[0m' == '\x1b[38;2;249;38;114m━━━━━\x1b[0m\x1b[38;2;249;38;114m╸\x1b[0m\x1b[38;5;237m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\x1b[0m'

test_bar.py:35: AssertionError
=========================== short test summary info ===========================
FAILED test_bar.py::test_render - AssertionError: assert '\x1b[38;2;249;38;11...
============================== 1 failed in 0.19s ==============================

Process finished with exit code 0

Assertion failed

Assertion failed
```

This specific test could possibly be failing because of line 5: `from render import render`. What package is this?

**Comment by willmcgugan** [comment]
Ah, you're on Windows. Rich renders a few things a little differently if it detects Windows, as cmd.exe doesn't support some unicode characters such as those used rendering progress bars.

I think the solution may be a flag on the Console object to override the Windows auto-detection, so the the output is the same as OSX/Linux.

> This specific test could possibly be failing because of line 5: from render import render. What package is this?

Thats importing from render.py in the same directory. Not sure why it's not finding that file.

So there's obviously a bit of work to do to support development on Windows, and setting up a development environment in general. I think I will look at that next. Perhaps I should merge your PR as is (test fails are minor and easy fixed). Then I'll work on the Windows / dev environment issues. How does that sound?

**Comment by sondrelg** [comment]
Sounds great 👍

**Comment by willmcgugan** [comment]
I've done the work in another branch, and also cleaned up the unused imports. Thanks for prompting me to do this, it was overdue.

**Pull request closed without merging**
