### PR TITLE
add progress component that works cleanly with Live

### PR DESCRIPTION
**Pull request by nathanrpage97**
## Type of changes

- [ ] Bug fix
- [x] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [x] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Creation of a `ProgressComponent` that extends Progress to work nicely with `Live`. As detailed in #482.

Renaming the class may be useful as it feels a bit lengthy.

### CODE REVIEW

**Comment by nathanrpage97** [comment]
Ok I think this is now at a reasonable setup, where it is convenient to call by the user.

**Review by ksj22000 — APPROVED** [review]

**Comment by agravier** [comment]
You may want to add a note in the Live documentation page as well, liking to the _Combining with Live_ section in the Progress page.

**Comment by willmcgugan** [comment]
Hi @nathanrpage97 

I see the need for this, bit I'm not keen on this `RenderProgress` class with stubs for `start()` etc.

Could we factor out a `ProgressRenderable` that handles the state and rendering, and extend that with the refresh thread etc to create the Progress class.

In psuedo-code...

```python
class ProgressRenderable:
    def add_task(self, ...):
        ...
    def __rich_console__(self,...):
        ...

class Progress(ProgressRenderable):
    def start(self):
        ...
```

Essentially adding functionality to the renderable to create a Progress class, rather than subtracting from Progress to create a renderable -- if that makes sense!

**Comment by nathanrpage97** [comment]
I was going to do it that way, the issue I had is that it would imply to a users IDE that the `Progress` component is `RichRenderable ` when it is not. Even if you were to add a `NotImplemented` exception to the `__rich_console__` of `Progress` in this case. Thoughts?

**Comment by willmcgugan** [comment]
> I was going to do it that way, the issue I had is that it would imply to a users IDE that the Progress component is RichRenderable when it is not.

I think it would be Rich renderable. It wouldn't be the recommended way to use Progress, but I don't see any harm in being able to do `console.print(progress)`.

**Comment by nathanrpage97** [comment]
Alright sounds good, I will refactor it tonight. I still want to keep the static `renderable()` method on `Progress` to keep it as 1 import that users will realistically  need from `rich.progress`.

**Comment by willmcgugan** [comment]
@nathanrpage97 You might want to hold off. I'd like to refactor Progress so that it uses the functionality in Live. I'm also thinking about ways to supported nested Live / Progress.

**Comment by nathanrpage97** [comment]
Alright all good. That makes a lot of sense. Should this pr be closed?

**Pull request closed without merging**
