### PR TITLE
Add markup support to log handler

### PR DESCRIPTION
**Pull request by furunkel**
## Type of changes

- [ ] Bug fix
- [x] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [ ] I've run the latest [black](https://github.com/ambv/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Please describe your changes here. If this fixes a bug, please link to the issue, if possible.

### CODE REVIEW

**Comment by willmcgugan** [comment]
Not convinced this is a good idea. Granted is off by default, but as convenient as console markup is, you risk hiding messages containing square brackets. Often log messages come from external libraries that will be out of your control.

Would the `highlighter` option not serve your needs? You can highlight something based on a regex.

**Comment by furunkel** [comment]
Using a `highlighter` would be quite painful. Good point though. It should be possible to use [setLogRecordFactory](https://docs.python.org/3/library/logging.html#logging.setLogRecordFactory) to install a custom factory function; this way the `markup` parameter would move to the actual log calls. Would that do?

**Comment by willmcgugan** [comment]
That sounds like a good idea.

**Comment by furunkel** [comment]
Passing it inside the `extra` dict does the trick. PR updated.

**Comment by willmcgugan** [comment]
Good solution 👍

**Pull request merged**
