### PR TITLE
Add additional check in __get__ for _Bit class

### PR DESCRIPTION
**Pull request by kylepollina**
## Type of changes

- [x] Bug fix
- [ ] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Fix a bug when trying to access attributes of uninitialized `Style` class.

Before change:

```python
Python 3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from rich.style import Style
>>> Style.blink
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kyle/projects/rich/rich/style.py", line 26, in __get__
    if obj._set_attributes & self.bit:
AttributeError: 'NoneType' object has no attribute '_set_attributes'
```

After change:
```python
Python 3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from rich.style import Style
>>> Style.blink
>>>
```

Accessing an attribute of an uninstantiated class sends `None` as the first argument to `__get__`. Example:
```python
>>> class Foo:
...     def __get__(self, instance, owner):
...             print("instance: ", instance)
...             print("owner: ", owner)
...
>>> class Bar:
...     foo = Foo()
...
>>> Bar.foo
instance:  None
owner:  <class '__main__.Bar'>
>>>
```

I'm not sure if this behavior is intended or not? I don't know the reasoning behind the design of this `__get__` function. Also I just assumed to return `None`. We could also return `self.bit` instead.

### CODE REVIEW

**Comment by willmcgugan** [comment]
I don't know of a situation where you would need to access that property without an instance. Do you have a use-case for this?

**Comment by kylepollina** [comment]
My use case is that I am assuming everything that is returned by `dir()` is an accessible attribute, but maybe I shouldn't assume that? I'm building an object explorer program, similar to how `rich.inspect` works but with some more features: https://github.com/kylepollina/objexplore/

Ran into an attribute error which led me down a small rabbit hole which helped me learn a little bit on how `__get__` works

If you don't think that this is worth adding that's fine by me :) You can just close

**Comment by willmcgugan** [comment]
Ah. I'm afraid you can't assume that. You will encounter many more examples of attributes where accessing them throws an exception.

Your object explorer looks very cool, BTW.

**Comment by kylepollina** [comment]
Thanks! It looks like you've sent some traffic over to it too ;)

**Pull request closed without merging**
