### PR TITLE
progressbar use decimal units

### PR DESCRIPTION
**Pull request by oleksis**
## Type of changes

- [x] Bug fix
- [ ] New feature
- [ ] Documentation / docstrings
- [x] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

#323

### CODE REVIEW

**Comment by oleksis** [comment]
Hi @willmcgugan 

About the tests y README, what we need update?

**Comment by willmcgugan** [comment]
@oleksis There is already a [PR](https://github.com/willmcgugan/rich/pull/326) in the works for this one. Probably should wait for @amartya-dev

But yeah, changelog and test will be required...

**Comment by oleksis** [comment]
@willmcgugan 
> But yeah, changelog and test will be required...
I added the required test and changelog

**Comment by willmcgugan** [comment]
Work done in https://github.com/willmcgugan/rich/pull/326 Thanks anyway!

**Pull request closed without merging**
